# Generated by Django 4.2.3 on 2023-08-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
